### ISSUE TITLE
does this run puppeteer in the browser?

### ISSUE THREAD

**Issue by whydna** [browserless/debugger#28]

**Comment by andyMrtnzP** [comment]
Yes, but only the `puppeteer-core` code. Behind the scenes, `puppeteer-core`  uses websockets, and some abstractions to handle the connection. So this can be packaged to run in the browser.

**Comment by andyMrtnzP** [comment]
The main file that does that is https://github.com/browserless/debugger/blob/main/src/puppeteer.worker.ts

**Comment by whydna** [comment]
so cool. tnx!
